//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_FINANCIERAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTIDADES_FINANCIERAS()
        {
            this.PRESTAMOS = new HashSet<PRESTAMOS>();
        }
    
        public decimal ID_ENTIDAD { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> NIT { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMOS> PRESTAMOS { get; set; }
    }
}
