//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVERSIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVERSIONES()
        {
            this.PAGOS_INVERSIONES = new HashSet<PAGOS_INVERSIONES>();
        }
    
        public decimal ID_INVERSIONES { get; set; }
        public Nullable<decimal> ID_USUARIO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> PLAZO_DIAS { get; set; }
        public Nullable<System.DateTime> FECHA_INICIAL { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public Nullable<decimal> TASA_INTERES { get; set; }
        public string MODALIDAD { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS_INVERSIONES> PAGOS_INVERSIONES { get; set; }
    }
}
