//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProyecto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ENTIDADES_FINANCIERAS> ENTIDADES_FINANCIERAS { get; set; }
        public virtual DbSet<INVERSIONES> INVERSIONES { get; set; }
        public virtual DbSet<PAGOS_INVERSIONES> PAGOS_INVERSIONES { get; set; }
        public virtual DbSet<PAGOS_PRESTAMOS> PAGOS_PRESTAMOS { get; set; }
        public virtual DbSet<PRESTAMOS> PRESTAMOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
