//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS_INVERSIONES
    {
        public decimal ID_PAGO_INVERSIONES { get; set; }
        public Nullable<decimal> ID_INVERSIONES { get; set; }
        public Nullable<System.DateTime> FECHA_PROGRAMADA { get; set; }
        public Nullable<System.DateTime> INTERES_PROGRAMADO { get; set; }
        public string ESTADO_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBIDO { get; set; }
        public Nullable<decimal> MONTO_RECIBIDO { get; set; }
    
        public virtual INVERSIONES INVERSIONES { get; set; }
    }
}
